#!/bin/sh 

# Start Wallpaper
swww init
swww img $HOME/.config/hypr/Wallpapers/hashira.png &

# Start dunst
dunst &

# Start foot server 
foot --server &

# Start waybar
waybar -c $HOME/.config/waybar/hyprland/config -s $HOME/.config/waybar/hyprland/style.css  

