#!/bin/sh

op1="Suspend"
op2="Poweroff"
op3="Reboot"

ops="${op1}\n${op2}\n${op3}"

selected=$(echo -e $ops | bemenu -i -l 15 -p "Powermenu:" \
    --fn 'Iosevka Nerd Font 16px' \
    --nb '#16161e[FF]' --ff '#abb2bf[FF]' \
    --tb '#7aa2f7[FF]' --tf '#16161e[FF]' \
    --fb '#16161e[FF]' --ff '#abb2bf[FF]' \
    --hb '#7aa2f7[FF]' --hf '#16161e[FF]' \
    --ab '#16161e[FF]' --sf '#7aa2f7[FF]' \
  )

sleep 0.7

if [[ $selected == $op1 ]]; then
    systemctl suspend && swaylock --screenshots --effect-blur 7x5 --fade-in 0 
elif [[ $selected == $op2 ]]; then
    systemctl poweroff
elif [[ $selected == $op3 ]]; then
    systemctl reboot
fi
