#!/bin/sh

icon=$HOME/.config/hypr/icons/camera-photo-symbolic.svg

op1="Fullscreen"
op2="Selected Area"

ops="${op1}\n${op2}"

selected=$(echo -e $ops | bemenu -i -l 15 -p "Screenshot:" \
    --fn 'Iosevka Nerd Font 16px' \
    --nb '#16161e[FF]' --ff '#abb2bf[FF]' \
    --tb '#7aa2f7[FF]' --tf '#16161e[FF]' \
    --fb '#16161e[FF]' --ff '#abb2bf[FF]' \
    --hb '#7aa2f7[FF]' --hf '#16161e[FF]' \
    --ab '#16161e[FF]' --sf '#7aa2f7[FF]' \
  )

sleep 0.7

if [[ $selected == $op1 ]]; then
    IMG=/tmp/$(date | sed "s/\s/-/g" | sed "s/--/-/g").png && grim $IMG && cat $IMG | wl-copy && rm -rf $IMG && dunstify "Screenshot Clipped" -i $icon
elif [[ $selected == $op2 ]]; then
    grim -g "$(slurp)" -| wl-copy && dunstify "Screenshot Clipped" -i $icon
fi
