#!/bin/sh

icon=$HOME/.config/hypr/icons/camera-photo-symbolic.svg

op1="Fullscreen"
op2="Selected Area"

ops="${op1}\n${op2}"

selected=$(echo -e $ops | rofi -dmenu -theme ~/.config/rofi/launchers/type-4/screenshot.rasi drun -display-drun -p "󰄀 ")

sleep 0.3

if [[ $selected == $op1 ]]; then
    IMG=/tmp/$(date | sed "s/\s/-/g" | sed "s/--/-/g").png && grim $IMG && cat $IMG | wl-copy && rm -rf $IMG && dunstify "Screenshot Clipped" -i $icon
elif [[ $selected == $op2 ]]; then
    grim -g "$(slurp)" -| wl-copy && dunstify "Screenshot Clipped" -i $icon
fi
