#!/usr/bin/env bash

list_wallpapers() {
    for file in "$1"/*
    do
        if [[ -f "$file" ]]; then
            echo -en "$(basename "$file")\0icon\x1f$(realpath "$file")\n"
        fi
    done
}

selected_wallpaper="$(list_wallpapers $HYPR_WALLS |  rofi -dmenu -theme ~/.config/rofi/launchers/type-4/wallpaper-selector.rasi -p " ")"

if [[ -f "$selected_wallpaper" ]]; then
    exit 0;
fi

swww img "$HYPR_WALLS/$selected_wallpaper"
